version: '3.2'

services:

  cassandra:
    image: 5.9.211.60:5000/cassandra
    container_name: cassandra
    restart: always
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    volumes:
      - /application/data/cassandra/:/var/lib/cassandra

  push:
    build:
      context: .
      dockerfile: PushService.API/Dockerfile
    container_name: push
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "9091:80"
    networks:
      - example.network

  identity:
    build:
      context: .
      dockerfile: PushService.IdentityServer/Dockerfile
    container_name: identity
    restart: always
    networks:
      - example.network

  gateway:
    build:
      context: .
      dockerfile: PushService.Gateway/Dockerfile
    container_name: gateway
    restart: always
    ports:
      - "8090:80"
    networks:
      - example.network

networks:
  example.network:
    driver: bridge



